FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app
EXPOSE 443


COPY *.sln .
COPY "src/Core/GuitarShopApp.Domain/*.csproj" "src/Core/GuitarShopApp.Domain/"
COPY "src/Core/GuitarShopApp.Application/*.csproj" "src/Core/GuitarShopApp.Application/"
COPY "src/Infrastructure/GuitarShopApp.Infrastructure/*.csproj" "src/Infrastructure/GuitarShopApp.Infrastructure/"
COPY "src/Infrastructure/GuitarShopApp.Persistence/*.csproj" "src/Infrastructure/GuitarShopApp.Persistence/"
COPY "src/Presentation/GuitarShopApp.WebUI/*.csproj" "src/Presentation/GuitarShopApp.WebUI/"
COPY "src/Presentation/GuitarShopApp.WebAPI/*.csproj" "src/Presentation/GuitarShopApp.WebAPI/"
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS final-env
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "GuitarShopApp.WebAPI.dll"]